[dev]
port = 8888
targetPort = 3000
publish = "apps/web/dist"

[build]
command = "npm run build"
publish = "apps/web/dist"

[functions]
directory = "apps/server/src"
node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/index"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
