name = "koinsight-server"
compatibility_date = "2025-04-01"
compatibility_flags = [ "nodejs_compat" ]
main = "src/index.cloudflare.ts"

[observability]
enabled = true

[assets]
directory = "../web/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
